version: '3.0'
services:
  web:
    restart: always
    build: .
    env_file:
      - .env
    # ports:
    #   - $PORT:$PORT
    expose:
      - $PORT
    depends_on:
      - db
    networks:
      - backend
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tasks.rule=Host(`tasks.paudel.me`)"
      - "traefik.http.routers.tasks.entrypoints=websecure"
      - "traefik.http.routers.tasks.tls.certresolver=certbot"
  db:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
      - internal
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  backend:
    external: true
  internal:
    driver: bridge
