FROM python:slim
WORKDIR /app
# requirements.txt is generated by pdm
COPY server/requirements.txt .
RUN pip install -r requirements.txt
COPY server .
# WORKDIR /app/server

CMD exec uvicorn app:app --host "0.0.0.0" --port $PORT
