version: '3.0'
services:
  db:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    restart: always
    depends_on:
      - db
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    command:
      [
        "uvicorn",
        "app.app:app",
        "--port",
        "${PORT}",
        "--host",
        "0.0.0.0"
      ]
