version: '3.0'
services:
  db:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    restart: always
    depends_on:
      - db
    build: .
    env_file:
      - .env
    expose:
      - ${PORT}
    command:
      [
        "uvicorn",
        "app.app:app",
        "--port",
        "${PORT}",
        "--host",
        "0.0.0.0"
      ]
    networks:
      - backend

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tasks.rule=Host(`tasks.paudel.me`)"
      - "traefik.http.routers.tasks.entrypoints=websecure"
      - "traefik.http.routers.tasks.tls.certresolver=certbot"

networks:
  backend:
    external: true
