/* tslint:disable */
/* eslint-disable */
/**
 * Tasks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogoutInput
 */
export interface LogoutInput {
    /**
     * 
     * @type {string}
     * @memberof LogoutInput
     */
    token: string;
}

/**
 * Check if a given object implements the LogoutInput interface.
 */
export function instanceOfLogoutInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function LogoutInputFromJSON(json: any): LogoutInput {
    return LogoutInputFromJSONTyped(json, false);
}

export function LogoutInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoutInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function LogoutInputToJSON(value?: LogoutInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

