/* tslint:disable */
/* eslint-disable */
/**
 * Tasks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskOutput
 */
export interface TaskOutput {
    /**
     * 
     * @type {number}
     * @memberof TaskOutput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TaskOutput
     */
    task: string;
    /**
     * 
     * @type {boolean}
     * @memberof TaskOutput
     */
    done: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TaskOutput
     */
    due: Date;
}

/**
 * Check if a given object implements the TaskOutput interface.
 */
export function instanceOfTaskOutput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "task" in value;
    isInstance = isInstance && "done" in value;
    isInstance = isInstance && "due" in value;

    return isInstance;
}

export function TaskOutputFromJSON(json: any): TaskOutput {
    return TaskOutputFromJSONTyped(json, false);
}

export function TaskOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'task': json['task'],
        'done': json['done'],
        'due': (new Date(json['due'])),
    };
}

export function TaskOutputToJSON(value?: TaskOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'task': value.task,
        'done': value.done,
        'due': (value.due.toISOString()),
    };
}

