/* tslint:disable */
/* eslint-disable */
/**
 * Tasks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenOutput
 */
export interface TokenOutput {
    /**
     * 
     * @type {string}
     * @memberof TokenOutput
     */
    token: string;
    /**
     * 
     * @type {Date}
     * @memberof TokenOutput
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the TokenOutput interface.
 */
export function instanceOfTokenOutput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "expiresAt" in value;

    return isInstance;
}

export function TokenOutputFromJSON(json: any): TokenOutput {
    return TokenOutputFromJSONTyped(json, false);
}

export function TokenOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'expiresAt': (new Date(json['expires_at'])),
    };
}

export function TokenOutputToJSON(value?: TokenOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'expires_at': (value.expiresAt.toISOString()),
    };
}

