/* tslint:disable */
/* eslint-disable */
/**
 * Tasks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskUpdateInput
 */
export interface TaskUpdateInput {
    /**
     * 
     * @type {string}
     * @memberof TaskUpdateInput
     */
    task?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TaskUpdateInput
     */
    done?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TaskUpdateInput
     */
    due?: Date;
}

/**
 * Check if a given object implements the TaskUpdateInput interface.
 */
export function instanceOfTaskUpdateInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TaskUpdateInputFromJSON(json: any): TaskUpdateInput {
    return TaskUpdateInputFromJSONTyped(json, false);
}

export function TaskUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskUpdateInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'task': !exists(json, 'task') ? undefined : json['task'],
        'done': !exists(json, 'done') ? undefined : json['done'],
        'due': !exists(json, 'due') ? undefined : (new Date(json['due'])),
    };
}

export function TaskUpdateInputToJSON(value?: TaskUpdateInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task': value.task,
        'done': value.done,
        'due': value.due === undefined ? undefined : (value.due.toISOString()),
    };
}

