/* tslint:disable */
/* eslint-disable */
/**
 * Tasks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskCreateInput
 */
export interface TaskCreateInput {
    /**
     * 
     * @type {string}
     * @memberof TaskCreateInput
     */
    task: string;
    /**
     * 
     * @type {boolean}
     * @memberof TaskCreateInput
     */
    done?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TaskCreateInput
     */
    due?: Date;
}

/**
 * Check if a given object implements the TaskCreateInput interface.
 */
export function instanceOfTaskCreateInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "task" in value;

    return isInstance;
}

export function TaskCreateInputFromJSON(json: any): TaskCreateInput {
    return TaskCreateInputFromJSONTyped(json, false);
}

export function TaskCreateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCreateInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'task': json['task'],
        'done': !exists(json, 'done') ? undefined : json['done'],
        'due': !exists(json, 'due') ? undefined : (new Date(json['due'])),
    };
}

export function TaskCreateInputToJSON(value?: TaskCreateInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task': value.task,
        'done': value.done,
        'due': value.due === undefined ? undefined : (value.due.toISOString()),
    };
}

