/* tslint:disable */
/* eslint-disable */
/**
 * Tasks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOutput
 */
export interface UserOutput {
    /**
     * 
     * @type {number}
     * @memberof UserOutput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserOutput
     */
    username: string;
}

/**
 * Check if a given object implements the UserOutput interface.
 */
export function instanceOfUserOutput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function UserOutputFromJSON(json: any): UserOutput {
    return UserOutputFromJSONTyped(json, false);
}

export function UserOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
    };
}

export function UserOutputToJSON(value?: UserOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'username': value.username,
    };
}

